Algoritmo "Exercício 04"


// Faça um algoritmo que some dois numeros simples entre eles.


Var

primeiro_numero, segundo_numero, soma: real


Inicio

      Escreva("Digite o primeiro valor: ")
      leia(primeiro_numero)
      Escreva("Digite o segundo valor: ")
      leia(segundo_numero)
      
      soma <- primeiro_numero + segundo_numero
      
      Escreva("A soma entre o número", primeiro_numero, " e o número", segundo_numero, " é igual a", soma)

Fimalgoritmo