Algoritmo "Exercício 6"


// Programa que mostra o número inteiro, seu antecesso e seu sucessor

Var

valor, antecessor, sucessor: inteiro


Inicio

      Escreva("Digite o número desejado: ")
      leia(valor)
      
      antecessor <- valor - 1
      sucessor <- valor + 1
      
      EscrevaL("O valor solicitado foi", valor, ". Seu sucessor é", sucessor, " e seu antecessor é", antecessor, ".")



Fimalgoritmo