Algoritmo "Exercício 87"
// 87) Crie um programa que melhore o procedimento Gerador() da questão anterior
// para que mostre uma mensagem personalizada, passada como parâmetro.
// Ex: Ao chamar Gerador("Aprendendo Portugol") aparece:
// +-------=======------+
// Aprendendo Portugol
// +-------=======------+

Procedimento Gerador ()
inicio
EscrevaL("+-------=======------+")
EscrevaL("      Olá, Mundo!     ")
EscrevaL("+-------=======------+")

FimProcedimento
Var

Inicio

Gerador()

Fimalgoritmo