Algoritmo "Exercício 71"

// 71) Faça um programa que preencha automaticamente um vetor numérico com 8
// posições, conforme abaixo:
// 999 999 999 999 999 999 999 999
// 0 1 2 3 4 5 6 7
Var

Vet: vetor [1..7] de Inteiro
contador: inteiro

Inicio

      Para contador <- 1 ate 7 faca
           Vet[contador] <- 999
           Escreva(Vet[contador])
           EscrevaL(contador)
      FimPara
           


Fimalgoritmo