Algoritmo "Exercício 07"

//Crie um algoritmo que leia um número real e mostre na tela o seu dobro e sua terça parte.


Var
dobro, terca_parte, valor: real


Inicio

      Escreva("Digite um valor: ")
      leia(valor)
      
      dobro <- valor  * 2
      terca_parte <- valor / 3
      
      EscrevaL("O dobro de ", valor, " é ", dobro, ".")
      EscrevaL("A terça parte de ", valor, " é ", terca_parte:1:4, ".")


Fimalgoritmo