Algoritmo "Exercicio 86"

// 86) Crie um programa que tenha um procedimento Gerador() que, quando chamado,
// mostre a mensagem "Olá, Mundo!" com algum componente visual (linhas)
// Ex: Ao chamar Gerador() aparece:
// +-------=======------+
// Olá, Mundo!
// +-------=======------+

Procedimento Gerador ()
inicio
EscrevaL("+-------=======------+")
EscrevaL("      Olá, Mundo!     ")
EscrevaL("+-------=======------+")

FimProcedimento
Var

Inicio

Gerador()

Fimalgoritmo