Algoritmo "Exercicio 90"

 // 90) Desenvolva um algoritmo que leia dois valores pelo teclado e passe esses
 // valores para um procedimento Somador() que vai calcular e mostrar a soma entre
 // eles.
 
Var

A, B: inteiro

Procedimento Somador (var X, Y: Inteiro)

Inicio

X <- X
Y <- Y

EscrevaL("A soma vale: ", X+Y)

FimProcedimento

Inicio

      EscrevaL("Primeiro valor: ")
      leia(A)
      EscrevaL("Segundo valor: ")
      leia(B)

      Somador(A, B)
Fimalgoritmo