Algoritmo "Exercício 5"


// Algoritmo que soma duas notas e faz a média de um aluno

Var

primeira_nota, segunda_nota, media: real


Inicio

      Escreva("Primeira nota: ")
      leia(primeira_nota)
      Escreva("Segunda nota: ")
      leia(segunda_nota)
      
      media <- (primeira_nota + segunda_nota) / 2
      
      EscrevaL("A média das notas", primeira_nota, " e", segunda_nota, " é igual a:", media)


Fimalgoritmo